// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO2Y6EloxWLLAzI7GTqsL7UYrA2KvJ2L0',
    appId: '1:112288452081:web:e12d3d9cdadb0fa9c04850',
    messagingSenderId: '112288452081',
    projectId: 'ambulance-service-ebccd',
    authDomain: 'ambulance-service-ebccd.firebaseapp.com',
    storageBucket: 'ambulance-service-ebccd.firebasestorage.app',
    measurementId: 'G-L6MVM28ZYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8dTcIQ_u4UYY9DKreExt1gH-dtPKB98',
    appId: '1:112288452081:android:4401b838c8f9a909c04850',
    messagingSenderId: '112288452081',
    projectId: 'ambulance-service-ebccd',
    storageBucket: 'ambulance-service-ebccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZa8ajH2Fl_wKOm_p-iF_hCUTBpOlR2zE',
    appId: '1:112288452081:ios:58b507dd371e718ac04850',
    messagingSenderId: '112288452081',
    projectId: 'ambulance-service-ebccd',
    storageBucket: 'ambulance-service-ebccd.firebasestorage.app',
    iosBundleId: 'com.example.notificationAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZa8ajH2Fl_wKOm_p-iF_hCUTBpOlR2zE',
    appId: '1:112288452081:ios:58b507dd371e718ac04850',
    messagingSenderId: '112288452081',
    projectId: 'ambulance-service-ebccd',
    storageBucket: 'ambulance-service-ebccd.firebasestorage.app',
    iosBundleId: 'com.example.notificationAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO2Y6EloxWLLAzI7GTqsL7UYrA2KvJ2L0',
    appId: '1:112288452081:web:dd291d5349d01fb2c04850',
    messagingSenderId: '112288452081',
    projectId: 'ambulance-service-ebccd',
    authDomain: 'ambulance-service-ebccd.firebaseapp.com',
    storageBucket: 'ambulance-service-ebccd.firebasestorage.app',
    measurementId: 'G-6HNYJ9VH3D',
  );
}
